export const TREATMENT_MAP = {
    'Apple Scab': { urgency: 'High', organic: 'Neem oil spray (2-3%), sulfur-based fungicide', chemical: 'Mancozeb 75% WP at 2g/L, Captan 50% WP at 2.5g/L', prevention: 'Remove fallen leaves, improve air circulation, choose resistant varieties', recovery: '2-4 weeks with treatment' },
    'Apple Black Rot': { urgency: 'High', organic: 'Copper fungicide spray, remove infected fruit', chemical: 'Thiophanate-methyl at 1g/L, Myclobutanil at 0.5g/L', prevention: 'Prune dead wood, remove mummified fruit, maintain tree hygiene', recovery: '3-5 weeks' },
    'Apple Cedar Rust': { urgency: 'Medium', organic: 'Remove nearby juniper trees, sulfur spray', chemical: 'Myclobutanil at 0.5g/L, Triadimefon at 0.5g/L', prevention: 'Eliminate alternate hosts, choose resistant varieties', recovery: '4-6 weeks' },
    'Cherry Powdery Mildew': { urgency: 'Medium', organic: 'Potassium bicarbonate spray, milk solution (40%)', chemical: 'Trifloxystrobin at 0.5g/L, Sulfur 80% WDG at 3g/L', prevention: 'Ensure good air flow, avoid overhead watering', recovery: '2-3 weeks' },
    'Corn Gray Leaf Spot': { urgency: 'Medium', organic: 'Crop rotation, remove crop residue', chemical: 'Azoxystrobin at 1ml/L, Propiconazole at 1ml/L', prevention: 'Rotate with non-host crops, use resistant hybrids', recovery: '3-4 weeks' },
    'Corn Common Rust': { urgency: 'Medium', organic: 'Plant resistant varieties', chemical: 'Mancozeb at 2.5g/L, Propiconazole at 1ml/L', prevention: 'Early planting, use resistant hybrids', recovery: '2-3 weeks' },
    'Corn Northern Leaf Blight': { urgency: 'High', organic: 'Crop rotation, residue destruction', chemical: 'Azoxystrobin at 1ml/L, Pyraclostrobin at 0.5ml/L', prevention: 'Plant resistant hybrids, rotate crops for 2+ years', recovery: '3-5 weeks' },
    'Grape Black Rot': { urgency: 'High', organic: 'Remove infected clusters, sulfur spray', chemical: 'Myclobutanil at 0.5g/L, Mancozeb at 2g/L', prevention: 'Prune for air circulation, remove mummies', recovery: '4-6 weeks' },
    'Grape Esca': { urgency: 'Critical', organic: 'Pruning wound protection, trunk renewal', chemical: 'No effective chemical treatment — management only', prevention: 'Protect pruning wounds, use certified planting material', recovery: 'Chronic — manage symptoms' },
    'Grape Leaf Blight': { urgency: 'Medium', organic: 'Remove infected leaves, improve drainage', chemical: 'Copper oxychloride at 3g/L, Mancozeb at 2.5g/L', prevention: 'Avoid overhead irrigation, ensure good canopy management', recovery: '3-4 weeks' },
    'Orange Haunglongbing': { urgency: 'Critical', organic: 'Remove infected trees, control psyllid vector', chemical: 'Imidacloprid for psyllid control, nutritional sprays', prevention: 'Use certified disease-free nursery stock, vector control', recovery: 'No cure — management only' },
    'Peach Bacterial Spot': { urgency: 'Medium', organic: 'Copper spray at dormancy', chemical: 'Oxytetracycline at 1g/L, Copper hydroxide at 2g/L', prevention: 'Choose resistant varieties, avoid overhead irrigation', recovery: '4-6 weeks' },
    'Pepper Bacterial Spot': { urgency: 'High', organic: 'Copper-based bactericide, remove infected plants', chemical: 'Streptomycin sulfate at 0.5g/L, Copper hydroxide at 2g/L', prevention: 'Use certified seed, rotate crops, avoid wet foliage', recovery: '3-5 weeks' },
    'Potato Early Blight': { urgency: 'Medium', organic: 'Copper fungicide, crop rotation', chemical: 'Chlorothalonil at 2g/L, Mancozeb at 2.5g/L', prevention: 'Rotate with non-solanaceous crops, adequate fertilization', recovery: '2-4 weeks' },
    'Potato Late Blight': { urgency: 'Critical', organic: 'Copper fungicide, destroy infected plants', chemical: 'Metalaxyl + Mancozeb at 2.5g/L, Cymoxanil at 1g/L', prevention: 'Use certified seed, destroy volunteer plants', recovery: '1-3 weeks if caught early' },
    'Squash Powdery Mildew': { urgency: 'Medium', organic: 'Potassium bicarbonate, neem oil', chemical: 'Myclobutanil at 0.5g/L, Sulfur 80% at 3g/L', prevention: 'Space plants well, avoid overhead watering', recovery: '2-3 weeks' },
    'Strawberry Leaf Scorch': { urgency: 'Medium', organic: 'Remove infected leaves, improve drainage', chemical: 'Captan 50% WP at 2g/L, Copper hydroxide at 2g/L', prevention: 'Use resistant varieties, renovate beds after harvest', recovery: '3-4 weeks' },
    'Tomato Bacterial Spot': { urgency: 'High', organic: 'Copper spray, remove infected plants', chemical: 'Streptomycin at 0.5g/L, Copper hydroxide at 2g/L', prevention: 'Use disease-free transplants, rotate crops', recovery: '3-5 weeks' },
    'Tomato Early Blight': { urgency: 'Medium', organic: 'Copper fungicide, mulching', chemical: 'Chlorothalonil at 2g/L, Mancozeb at 2.5g/L', prevention: 'Stake plants, remove lower leaves, mulch', recovery: '2-4 weeks' },
    'Tomato Late Blight': { urgency: 'Critical', organic: 'Copper fungicide, destroy infected plants immediately', chemical: 'Metalaxyl + Mancozeb at 2.5g/L', prevention: 'Use resistant varieties, avoid overhead irrigation', recovery: '1-2 weeks if caught immediately' },
    'Tomato Leaf Mold': { urgency: 'Medium', organic: 'Improve ventilation, reduce humidity', chemical: 'Chlorothalonil at 2g/L, Mancozeb at 2g/L', prevention: 'Ensure greenhouse ventilation, use resistant varieties', recovery: '2-3 weeks' },
    'Tomato Septoria Leaf Spot': { urgency: 'Medium', organic: 'Remove infected leaves, mulch heavily', chemical: 'Chlorothalonil at 2g/L, Copper fungicide at 2g/L', prevention: 'Rotate crops, stake plants, avoid overhead watering', recovery: '3-4 weeks' },
    'Tomato Spider Mites': { urgency: 'High', organic: 'Neem oil, insecticidal soap, introduce predatory mites', chemical: 'Abamectin at 0.5ml/L, Spiromesifen at 0.5ml/L', prevention: 'Maintain humidity, avoid dusty conditions', recovery: '1-2 weeks' },
    'Tomato Target Spot': { urgency: 'Medium', organic: 'Copper fungicide, remove infected leaves', chemical: 'Chlorothalonil at 2g/L, Azoxystrobin at 1ml/L', prevention: 'Improve air circulation, rotate crops', recovery: '2-4 weeks' },
    'Tomato Yellow Leaf Curl Virus': { urgency: 'Critical', organic: 'Remove infected plants, control whiteflies with sticky traps', chemical: 'Imidacloprid for whitefly control', prevention: 'Use resistant varieties, reflective mulches, screen transplants', recovery: 'No cure — remove and replant' },
    'Tomato Mosaic Virus': { urgency: 'Critical', organic: 'Remove infected plants, sanitize tools', chemical: 'No chemical treatment — virus management only', prevention: 'Use resistant varieties, sanitize hands and tools', recovery: 'No cure — remove infected plants' },
};

export function getTreatment(diseaseName) {
    return TREATMENT_MAP[diseaseName] || null;
}
